### ISSUE TITLE
Probems with current version of the SDFat library

### ISSUE THREAD

**Issue by robinhedwards** [whizzosoftware/SIO2Arduino#3]
Daniel,
Thanks for an excellent project that has breathed some life into my old 65XE which I dusted off after about 20 years.

I had a small problem getting things working with the current version of SDFat:
readDir() seems to not reliably step through the files if a file.open() takes place.
The result is that you can only cycle through a small subset of the files in the directory. Commenting out the file.open() shows all the files.

However, I figured your code was probably good, so I downloaded an older copy of the library (sdfatlib20130629.zip) and it worked prefectly.

Robin

**Comment by miketum** [comment]
Good Day, friends, from Russia!
I've compiled Your code, it works correctly (after some troubles)!
But the question: I cannot insert Fast SIO (up to 127 kb.) via Atari command $3F.
Have You an experience? Prob. a code?
Mikle from Moscow.

**Comment by zaztaz** [comment]
Hello Dan, 
what a wonderful project. I can recycle my cable sio2pc !!

Sorry I'm new in arduino programming 

I have some compilation errors
SIO2Arduino:38: error: 'getDeviceStatus' was not declared in this scope
 DriveAccess driveAccess(getDeviceStatus, readSector, writeSector, format);
                         ^
SIO2Arduino:38: error: 'readSector' was not declared in this scope
 DriveAccess driveAccess(getDeviceStatus, readSector, writeSector, format);
                                          ^
SIO2Arduino:38: error: 'writeSector' was not declared in this scope
 DriveAccess driveAccess(getDeviceStatus, readSector, writeSector, format);
                                                      ^
SIO2Arduino:38: error: 'format' was not declared in this scope
 DriveAccess driveAccess(getDeviceStatus, readSector, writeSector, format);
                                                                   ^
SIO2Arduino:39: error: 'getFileList' was not declared in this scope
 DriveControl driveControl(getFileList, mountFileIndex, changeDirectory);
                           ^
SIO2Arduino:39: error: 'mountFileIndex' was not declared in this scope
 DriveControl driveControl(getFileList, mountFileIndex, changeDirectory);
                                        ^
SIO2Arduino:39: error: 'changeDirectory' was not declared in this scope
 DriveControl driveControl(getFileList, mountFileIndex, changeDirectory);
                                                        ^
Using library SdFat in folder: C:\Users\-\Documents\Arduino\libraries\SdFat (legacy)
exit status 1

Eric from France

**Comment by abcbarryn** [comment]
Regarding miketum's question:
I cannot insert Fast SIO (up to 127 kb.) via Atari command $3F.

It is unlikely that higher speeds will work due to the 16Mhz clock on the Arduino causing slight inaccuracies in the communications at higher serial baud rates. You might get it to work if you change the clock crystal on the arduino board.

Regarding zaztaz's compilation errors:
Try using branch abcbarryn-master, and make sure you are using the current SDFat library.

**Comment by miketum** [comment]
Thank You for Your answer.I wanted to change SIO speed via Atari command $3F in C arduino program, but failed.I know, by the way, that similar controller on standard Atmel (16 Mhz.) can do this....too few information about $3F command... 25.01.2016, 19:22, "Barry Nelson" <notifications@github.com>:Regarding miketum's question: I cannot insert Fast SIO (up to 127 kb.) via Atari command $3F.It is unlikely that higher speeds will work due to the 16Mhz clock on the Arduino causing slight inaccuracies in the communications at higher serial baud rates. You might get it to work if you change the clock crystal on the arduino board.Regarding zaztaz's compilation errors: Try using branch abcbarryn-master, and make sure you are using the current SDFat library.—Reply to this email directly or view it on GitHub.

**Comment by Zemac** [comment]
Regarding Eric's from France question:
Hi, Eric.
If you want this code to run on the current Arduino IDE and need sdfat old library (ver.21.9.2013). It was also necessary to insert a code library SPI.h.
Library and sketch can be found at this link. The code is already set on the control button and there is the added library SPI.h. The code is functional in the Arduino IDE 1.6.5.
https://drive.google.com/file/d/0BwX94lwwuDfzcEdrUm1ub29VQm8/view?usp=sharing
Hello Zemáč
From Czech Republic

**Comment by abcbarryn** [comment]
I built it using this version of SdFat
/** SdFat version YYYYMMDD */
#define SD_FAT_VERSION 20150324

And the Arduino IDE version 1.6.5

Make sure to select the branch abcbarryn-master instead of just master.

The SdFat library is available at: https://github.com/greiman/SdFat

If you have any problems with that branch on Arduino IDE 1.6.5 with that version of SdFat post them here and I will try to assist.

**Comment by james7780** [comment]
Does not compile using the "current" version of SdFat as specified in readme.txt.
But I did manage to compile it for Arduino Uno + EtherNet shield, using Arduino IDE 1.6.5 and older version of SdFat (see Zemac's link above).
IDE warns of low available Uno RAM, and runs out of Uno RAM if you enable the debug logging in config.h.
I have not connected it to my 600XL yet to see if it actually works. If it doesn't I will try compile for my Leonardo (which has slightly more RAM).

**Comment by cbmeeks** [comment]
Everyone, seems there are several different issues going on.  Wouldn't it be better to create an individual issue per problem instead of combining them all into this one?

Just a thought, anyway...

**Comment by high500** [comment]
Use the old version of sdfat as suggested and old Arduino 1.65 plus I had to replace any instances of an invalid call to file->getName:

Change this:

`file->getName((char*)&filename, 13);`

to:

`file->getFilename((char*)&filename);`

I know at least one reference is used in disk_image.cpp but check all the SIO2Arduino files (do not modify the SDFat files)

This worked for me!
